version: "3.9"

name: pms-prod

services:
  db:
    image: postgres:16-alpine
    env_file:
      - apps/api/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  prod:
    image: node:20.18.0-slim
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    restart: unless-stopped
    command: >-
      sh -c "apt-get update -y && apt-get install -y --no-install-recommends openssl &&
      corepack enable && corepack prepare yarn@1.22.22 --activate &&
      yarn install --frozen-lockfile --production=false &&
      yarn --cwd apps/api prisma:generate &&
      yarn build &&
      yarn --cwd apps/api prisma:deploy &&
      if [ \"$SEED\" = \"true\" ]; then yarn --cwd apps/api prisma:seed; fi &&
      PORT=3001 yarn --cwd apps/api start:prod &
      HOSTNAME=0.0.0.0 PORT=3000 yarn --cwd apps/web start &
      wait"
    env_file:
      - apps/api/.env
      - apps/web/.env
    environment:
      NODE_ENV: production
      SEED: ${SEED:-}
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - turbo_cache:/app/.turbo

volumes:
  db_data:
  node_modules:
  turbo_cache:
