version: "3.9"

name: pms-dev

services:
  db:
    image: postgres:16-alpine
    env_file:
      - apps/api/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  dev:
    image: node:20.18.0-slim
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    command: sh -c "[ -d node_modules ] || yarn install --frozen-lockfile && chmod +x scripts/dev-root-entrypoint.sh && scripts/dev-root-entrypoint.sh"
    env_file:
      - apps/api/.env
      - apps/web/.env
    environment:
      CHOKIDAR_USEPOLLING: "1"
      WATCHPACK_POLLING: "true"
      SEED: ${SEED:-}
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - turbo_cache:/app/.turbo

volumes:
  db_data:
  node_modules:
  turbo_cache:
